# Generated by Django 4.2.1 on 2023-05-17 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='ингредиент')),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'ингредиент',
                'verbose_name_plural': 'ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='название')),
                ('hexcode', models.CharField(max_length=16)),
                ('slug', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='название')),
                ('slug', models.CharField(max_length=16, unique=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='recipes/images/', verbose_name='Фотография')),
                ('description', models.TextField(verbose_name='текстовое описание')),
                ('time', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='автор публикации')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredient', verbose_name='ингредиент')),
                ('tag', models.ForeignKey(max_length=16, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.tag', verbose_name='тег')),
            ],
            options={
                'verbose_name': 'рецепт',
                'verbose_name_plural': 'рецепты',
            },
        ),
    ]
